<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>dev.arcovia.mitigation</groupId>
		<artifactId>parent</artifactId>
		<version>1.0.0-SNAPSHOT</version>
		<relativePath>../</relativePath>
	</parent>
	<groupId>dev.arcovia.mitigation</groupId>
	<artifactId>tests</artifactId>	
	<version>1.0.0-SNAPSHOT</version>
	<packaging>pom</packaging>

	<modules>
		<module>dev.arcovia.mitigation.sat.tests</module>
		<module>dev.arcovia.mitigation.ilp.tests</module>
		<module>dev.arcovia.mitigation.smt.tests</module>
		<module>dev.arcovia.mitigation.ranking.tests</module>
		<module>dev.arcovia.mitigation.uncertainty.tests</module>
	</modules>
	
</project>
